updated structure, variable names and descriptions
CookieNoob/Ultimate-Maps-forged-alliance pull request #3
Opened 2018-05-20 11:02 UTC by badbwoi

and added optional_naval_wreckage, core_mexes, extra_mexes, jamming

2018-05-20 12:19 UTC, CookieNoob requested changes
die konvention mit dem unterstrich finde ich gut, aber einige kleinigkeiten müssen noch geändert werden (die default werte z.B.), da das script sonst abstürzt (auf einer neu erstellten map, also bevor änderungen gemacht wurden wie z.B. civ gruppen hinzugefügt werden)

2018-05-20 12:19 UTC, CookieNoob commented on mapname_options.lua
> +        { text = "used slots", help = "Spawn resources for player on used slots.", key = 2, },
diese option ist problematisch, da damit die map unbalanced wird...

2018-05-20 12:19 UTC, CookieNoob commented on mapname_options.lua
> +        { text = "8v8 setup", help = "Don't adjust for player & spawn resources for maximum player count.", key = 6, },
diese optionen würde ich zumindestens teilweise auskommentieren

2018-05-20 12:19 UTC, CookieNoob commented on mapname_options.lua
> -},
wieso hast du diese option entfernt?

2018-05-20 12:19 UTC, CookieNoob commented on mapname_options.lua
> +    label = "Crazyrush",
diese option ist "immer funktionsfähig", daher sollte sie nicht im auskommentierten bereich stehen

2018-05-20 12:19 UTC, CookieNoob commented on mapname_options.lua
> +    label = "Crazyrush",
die option forward sollte auskommentiert sein

2018-05-20 12:19 UTC, CookieNoob commented on mapname_options.lua
> +    default = 2,
default sollte identisch mit dem default im script sein (da steht zwar 2, aber das wird zu einem crash führen wenn keine civs definiert sind auch wenn die option auskommentiert wird)
ändern zu 1

2018-05-20 12:19 UTC, CookieNoob commented on mapname_script.lua
> +local optional_wreckage = ScenarioInfo.Options.optional_wreckage or 2
default ändern auf 1

2018-05-20 12:19 UTC, CookieNoob commented on mapname_script.lua
> +local optional_naval_wreckage = ScenarioInfo.Options.optional_naval_wreckage or 2
default ändern auf 1

2018-05-20 12:19 UTC, CookieNoob commented on mapname_script.lua
> +local optional_civilian_base = ScenarioInfo.Options.optional_civilian_base or 2
default ändern auf 1

2018-05-20 12:19 UTC, CookieNoob commented on mapname_script.lua
> +local optional_civilian_defenses = ScenarioInfo.Options.optional_civilian_defenses or 2
default ändern auf 1

2018-05-20 12:19 UTC, CookieNoob commented on mapname_script.lua
> +local extra_mexes = ScenarioInfo.Options.extra_mexes or 2
default ändern auf 1

2018-05-20 12:19 UTC, CookieNoob commented on mapname_script.lua
> +function OnStart()
OnStart sollte der Übersichtlichkeit halber über den startCrazy... und startGrowing... funktionen stehen

2018-05-20 12:19 UTC, CookieNoob commented on mapname_script.lua
> +--[[    --remove some of the rocks
dieser kommentarbereich kann entfernt werden (die funktion funktioniert nicht)

2018-05-20 12:19 UTC, CookieNoob commented on mapname_script.lua
> +    BroadcastMSG('If you see any bugs with the map, plz tell CookieNoob. Thx.',  -- message
'If you see any bugs with the map, plz tell CookieNoob. Thx.' ->
'If you see any bugs with the map, plz tell the map author. Thx.'

2018-05-20 12:19 UTC, CookieNoob commented on mapname_script.lua
> +    -- LOG("ADAPTIVE: optional_reclaim_middle = ", optional_reclaim_middle)
diese logs sollten nicht auskommentiert sein

2018-05-20 12:19 UTC, CookieNoob commented on mapname_script.lua
>          for m = 13, 14 do
das ist nur ein sehr spezieller fall, das sollte auskommentiert als block im code stehen, aber der normale fall sollte der code hier drunter sein (den du auskommentiert hast)

2018-05-20 12:19 UTC, CookieNoob commented on mapname_script.lua
> +        ScenarioUtils.CreateArmyGroup('ARMY_17', 'Optional_Civilian_Defenses_4', true)
```
+    if(optional_civilian_defenses == 2) then
+        ScenarioUtils.CreateArmyGroup('ARMY_17', 'Optional_Civilian_Defenses_2', true)
+    elseif(optional_civilian_defenses == 3) then
+        ScenarioUtils.CreateArmyGroup('ARMY_17', 'Optional_Civilian_Defenses_2', true)
+        ScenarioUtils.CreateArmyGroup('ARMY_17', 'Optional_Civilian_Defenses_3', true)
+    elseif(optional_civilian_defenses == 4) then
+        ScenarioUtils.CreateArmyGroup('ARMY_17', 'Optional_Civilian_Defenses_2', true)
+        ScenarioUtils.CreateArmyGroup('ARMY_17', 'Optional_Civilian_Defenses_3', true)
+        ScenarioUtils.CreateArmyGroup('ARMY_17', 'Optional_Civilian_Defenses_4', true)
```


dieser block kann einfach ersetzt werden durch
```
for i = 2, optional_civilian_defenses do
    ScenarioUtils.CreateArmyGroup('ARMY_17', 'Optional_Civilian_Defenses_' .. i, true)
```

2018-05-20 12:19 UTC, CookieNoob commented on mapname_script.lua
> +        ScenarioUtils.CreateArmyGroup('ARMY_17', 'Optional_Civilian_Defenses_4', false)
```
+    elseif(optional_civilian_defenses == 5) then
+        ScenarioUtils.CreateArmyGroup('ARMY_17', 'Optional_Civilian_Defenses_2', false)
+    elseif(optional_civilian_defenses == 6) then
+        ScenarioUtils.CreateArmyGroup('ARMY_17', 'Optional_Civilian_Defenses_2', false)
+        ScenarioUtils.CreateArmyGroup('ARMY_17', 'Optional_Civilian_Defenses_3', false)
+    elseif(optional_civilian_defenses == 7) then
+        ScenarioUtils.CreateArmyGroup('ARMY_17', 'Optional_Civilian_Defenses_2', false)
+        ScenarioUtils.CreateArmyGroup('ARMY_17', 'Optional_Civilian_Defenses_3', false)
+        ScenarioUtils.CreateArmyGroup('ARMY_17', 'Optional_Civilian_Defenses_4', false)
```

ist eine kopie vom code darüber und macht das selbe -> entfernen

2018-05-20 12:19 UTC, CookieNoob commented on mapname_script.lua
> +    -- LOG("ADAPTIVE: crazyrush_mexes = ", crazyrush_mexes)
diese logs sollten nicht auskommentiert sein

2018-05-20 12:19 UTC, CookieNoob commented on mapname_script.lua
> +        for m = 5, 16 do
benutzt nicht "maxPlayerOnMap"

2018-05-20 12:19 UTC, CookieNoob commented on mapname_script.lua
>          for m = 9, 16 do
benutzt nicht "maxPlayerOnMap"

2018-05-20 12:19 UTC, CookieNoob commented on mapname_script.lua
> +        for m = 13, 16 do
benutzt nicht "maxPlayerOnMap"

2018-05-20 12:19 UTC, CookieNoob commented on mapname_script.lua
> +            if(additional_hydros == 1) then
gute idee mit dieser konvention

2018-05-20 12:19 UTC, CookieNoob commented on mapname_script.lua
> +        0                        # ???
inzwischen ist klar, dass dieser parameter "fidelity" regelt... 
-> "???"  ersetzen durch "fidelity"

2018-05-20 12:19 UTC, CookieNoob commented on mapname_tables.lua
> +
ich habe es jetzt nicht überprüft, aber sind alle tabellen die im code verwendet werden wirklich auch hier aufgeführt?

2018-05-21 18:24 UTC, badbwoi commented on mapname_script.lua
> +        ScenarioUtils.CreateArmyGroup('ARMY_17', 'Optional_Civilian_Defenses_4', true)
Hier handelt es sich um Wrecks und lebende Einheiten, die aus den Gruppen 2, 3 & 4 bestehen. Dein vorgeschlagener Style macht Probleme wenn ich die Optionen 5-7 auswähle, da diese Gruppen nicht existieren.

2018-05-21 18:24 UTC, badbwoi commented on mapname_script.lua
> +        ScenarioUtils.CreateArmyGroup('ARMY_17', 'Optional_Civilian_Defenses_4', false)
Wie ebend beschrieben, werden hier die Einheiten lebend gespawned

2018-05-21 19:44 UTC, CookieNoob commented on mapname_script.lua
> +        ScenarioUtils.CreateArmyGroup('ARMY_17', 'Optional_Civilian_Defenses_4', true)
oh hab gar nicht gesehen dass das eine wracks sind xD

2018-05-21 20:21 UTC, CookieNoob commented on mapname_script.lua
> +    local mexsidebot = ScenarioInfo.Options.mexsidebot or 1 --not in options?
die map "Adaptive Wonder Open" hat oben rechts und unten links jeweils einzeln anpassbare mexe, daher kommt das hier... vielleicht einen kommentar dazu und sonst einfach drin lassen :)

2018-05-21 20:31 UTC, CookieNoob approved these changes

2018-05-21 20:52 UTC, CookieNoob commented
sieht gut aus

2018-05-21 20:52 UTC, merged